//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cost_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoices
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Invoices()
        {
            this.InvoiceDetail = new HashSet<InvoiceDetail>();
        }
    
        public string InvoicesNum { get; set; }
        public string Name { get; set; }
        public string Store { get; set; }
        public string InvoicePeriod { get; set; }
        public string InvoicesDate { get; set; }
        public string InvoicesTotal { get; set; }
        public string Value { get; set; }
        public string Note { get; set; }
        public string CustomerValue { get; set; }
        public string orderStatus { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ToolCode { get; set; }
        public string LoveCode { get; set; }
        public string Tax { get; set; }
        public string PayBy { get; set; }
        public string Cancel { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceDetail> InvoiceDetail { get; set; }
    }
}
