//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cost_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Products
    {
        public int Id { get; set; }
        public string ProductClass { get; set; }
        public string ProductionName { get; set; }
        public string ProductionContent0 { get; set; }
        public string ProductionContent1 { get; set; }
        public string ProductionContent2 { get; set; }
        public int Prices { get; set; }
        public List<Products> ListData { get; set; }
    }
}
