//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cost_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreInformation
    {
        public int Id { get; set; }
        public string StartNum { get; set; }
        public string EndNum { get; set; }
        public string Name { get; set; }
        public string Value { get; set; }
        public string Store { get; set; }
        public string StoreNumber { get; set; }
        public string StoreAddress { get; set; }
        public bool Status { get; set; }
        public string StoreCode { get; set; }
        public List<StoreInformation> ListData { get; set; }
    }
}
